name: Playwright Tests with Allure Report

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write    
jobs:
  run_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pw-practice-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  

      - name: Install dependencies
        run: npm ci --force

      - name: Install Allure CLI
        run: npm install -g allure-commandline         

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: DEV=1 npx playwright test usePageObject.spec.ts --project=chromium
        continue-on-error: true

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: pw-practice-app/allure-results

  generate_report:
    runs-on: ubuntu-latest
    needs: run_tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Restore Allure history
      #   run: |
      #     if [ -d allure-report/history ]; then
      #     mkdir -p allure-results/history
      #     cp -R allure-report/history/* allure-results/history/
      #     fi
      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: pw-practice-app/allure-results

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Allure historyy
        run: |
          if [ -d "gh-pages/history" ]; then
            echo "History found. Copying..."
            mkdir -p ./allure-results/history
            cp -r gh-pages/history/* ./allure-results/history || true
          else
            echo "No history found. First run?"
          fi

      - name: Install Allure CLI
        run: npm install -g allure-commandline   

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      
      # - name: Persist Allure history
      #   run: |
      #     mkdir -p gh-pages/history
      #     cp -R allure-report/history/* gh-pages/history/  

      # - name: Disable Jekyll
      #   run: touch allure-report/.nojekyll

      # - name: Prevent GitHub Pages caching
      #   run: |
      #     echo -e "/*\n  Cache-Control: no-cache\n" > allure-report/.headers  

      # - name: Add build timestamp
      #   run: |
      #     BUILD_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
      #     sed -i "s/<title>Allure Report<\/title>/<title>Allure Report - $BUILD_TIME<\/title>/" allure-report/index.html  

      - name: Deploy Allure report to GitHub Pagesd
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: pw-practice-app/allure-report

